"""PostgreSQL-backed registry with short-lived, transaction-scoped connections."""
from __future__ import annotations

import atexit
from pathlib import Path
import re
import threading
import time
from contextlib import contextmanager
from typing import Iterator

from backend import config
from backend.models import RelaxOption, Rule, Roster, Schedule

_pool = None
_pool_lock = threading.Lock()


def _close_pool():
    global _pool
    if _pool is not None:
        try:
            _pool.close()
        except Exception:
            pass
        _pool = None


atexit.register(_close_pool)


def _get_pool():
    global _pool
    if _pool is not None:
        return _pool
    with _pool_lock:
        if _pool is not None:
            return _pool
        try:
            from psycopg_pool import ConnectionPool
        except ImportError as exc:
            raise RuntimeError("PostgreSQL driver missing; install requirements.txt") from exc
        try:
            pool = ConnectionPool(
                conninfo=config.DATABASE_URL,
                min_size=1,
                max_size=10,
                timeout=10,
                kwargs={"connect_timeout": 5, "application_name": "gecompose-backend"},
                open=False,
            )
            pool.open(wait=True, timeout=10)
            _pool = pool
        except Exception as exc:
            raise RuntimeError(f"Cannot connect to PostgreSQL: {exc}") from exc
    return _pool


@contextmanager
def _connect() -> Iterator:
    try:
        from psycopg import OperationalError
        from psycopg_pool import PoolTimeout
    except ImportError as exc:
        raise RuntimeError("PostgreSQL driver missing; install requirements.txt") from exc
    try:
        pool = _get_pool()
        with pool.connection() as connection:
            yield connection
    except (OperationalError, PoolTimeout) as exc:
        raise RuntimeError(f"Cannot connect to PostgreSQL: {exc}") from exc


def init_db() -> None:
    statements = (
        "CREATE TABLE IF NOT EXISTS rules(id TEXT PRIMARY KEY,json TEXT NOT NULL,salt BYTEA,rule_hash TEXT,status TEXT NOT NULL)",
        "CREATE INDEX IF NOT EXISTS rules_status_id_idx ON rules(status,id)",
        "CREATE TABLE IF NOT EXISTS roster(id SMALLINT PRIMARY KEY CHECK(id=1),json TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS parsers(layout_signature TEXT PRIMARY KEY,code TEXT NOT NULL,created_at DOUBLE PRECISION NOT NULL)",
        "CREATE TABLE IF NOT EXISTS schedules(hash TEXT PRIMARY KEY,version INTEGER NOT NULL,json TEXT NOT NULL,tx_hash TEXT NOT NULL,created_at DOUBLE PRECISION NOT NULL)",
        "CREATE INDEX IF NOT EXISTS schedules_latest_idx ON schedules(version DESC,created_at DESC)",
        "CREATE TABLE IF NOT EXISTS options(id TEXT PRIMARY KEY,json TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS llm_calls(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,fn TEXT,model TEXT,tokens_in INTEGER,tokens_out INTEGER,ms INTEGER,mock BOOLEAN,ts DOUBLE PRECISION)",
        "CREATE INDEX IF NOT EXISTS llm_calls_timestamp_idx ON llm_calls(ts)",
        "CREATE TABLE IF NOT EXISTS id_sequences(name TEXT PRIMARY KEY,value BIGINT NOT NULL CHECK(value >= 0))",
    )
    with _connect() as connection:
        for statement in statements:
            connection.execute(statement)


def check_connection() -> None:
    with _connect() as connection:
        connection.execute("SELECT 1")


def reset_db(keep_parsers: bool = False) -> None:
    init_db()
    with _connect() as connection:
        for table in ("rules", "roster", "schedules", "options", "llm_calls", "id_sequences"):
            connection.execute(f"DELETE FROM {table}")
        if not keep_parsers:
            connection.execute("DELETE FROM parsers")


def save_roster(roster: Roster) -> None:
    with _connect() as connection:
        connection.execute(
            "INSERT INTO roster(id,json) VALUES(1,%s) ON CONFLICT(id) DO UPDATE SET json=EXCLUDED.json",
            (roster.model_dump_json(),),
        )


def get_roster() -> Roster:
    with _connect() as connection:
        row = connection.execute("SELECT json FROM roster WHERE id=1").fetchone()
    if row is None:
        raise LookupError("No roster is configured")
    return Roster.model_validate_json(row[0])


def _next_id(sequence: str, table: str, pattern: str, prefix: str) -> str:
    """Reserve an identifier atomically, accounting for fixed demo IDs."""
    with _connect() as connection:
        connection.execute(
            "INSERT INTO id_sequences(name,value) VALUES(%s,0) ON CONFLICT(name) DO NOTHING",
            (sequence,),
        )
        row = connection.execute(
            "SELECT value FROM id_sequences WHERE name=%s FOR UPDATE", (sequence,)
        ).fetchone()
        current = int(row[0])
        rows = connection.execute(f"SELECT id FROM {table}").fetchall()
        highest = max(
            (int(match.group(1)) for item in rows if (match := re.fullmatch(pattern, item[0]))),
            default=0,
        )
        value = max(current, highest) + 1
        connection.execute("UPDATE id_sequences SET value=%s WHERE name=%s", (value, sequence))
    return f"{prefix}{value}"


def next_rule_id() -> str:
    return _next_id("rules", "rules", r"R(\d+)", "R")


def save_rule(rule: Rule, salt: bytes | None = None, rule_hash: str | None = None) -> None:
    with _connect() as connection:
        connection.execute(
            """INSERT INTO rules(id,json,salt,rule_hash,status) VALUES(%s,%s,%s,%s,%s)
            ON CONFLICT(id) DO UPDATE SET json=EXCLUDED.json,
            salt=COALESCE(EXCLUDED.salt,rules.salt),
            rule_hash=COALESCE(EXCLUDED.rule_hash,rules.rule_hash),status=EXCLUDED.status""",
            (rule.id, rule.model_dump_json(), salt, rule_hash, rule.status),
        )


def get_rule(rule_id: str) -> Rule:
    with _connect() as connection:
        row = connection.execute("SELECT json FROM rules WHERE id=%s", (rule_id,)).fetchone()
    if not row:
        raise LookupError(f"Rule {rule_id} was not found")
    return Rule.model_validate_json(row[0])


def list_rules(status: str | None = None) -> list[Rule]:
    with _connect() as connection:
        if status is None:
            rows = connection.execute("SELECT json FROM rules ORDER BY id").fetchall()
        else:
            rows = connection.execute("SELECT json FROM rules WHERE status=%s ORDER BY id", (status,)).fetchall()
    return [Rule.model_validate_json(row[0]) for row in rows]


def get_salt(rule_id: str) -> bytes:
    with _connect() as connection:
        row = connection.execute("SELECT salt FROM rules WHERE id=%s", (rule_id,)).fetchone()
    if not row or row[0] is None:
        raise LookupError(f"Rule {rule_id} has no registered salt")
    return bytes(row[0])


def get_rule_hash(rule_id: str) -> str:
    with _connect() as connection:
        row = connection.execute("SELECT rule_hash FROM rules WHERE id=%s", (rule_id,)).fetchone()
    if not row or not row[0]:
        raise LookupError(f"Rule {rule_id} has no registered hash")
    return str(row[0])


def save_parser(sig: str, code: str) -> None:
    with _connect() as connection:
        connection.execute(
            "INSERT INTO parsers VALUES(%s,%s,%s) ON CONFLICT(layout_signature) DO UPDATE SET code=EXCLUDED.code,created_at=EXCLUDED.created_at",
            (sig, code, time.time()),
        )


def get_parser(sig: str) -> str | None:
    with _connect() as connection:
        row = connection.execute("SELECT code FROM parsers WHERE layout_signature=%s", (sig,)).fetchone()
    return row[0] if row else None


def delete_parser(sig: str) -> None:
    with _connect() as connection:
        connection.execute("DELETE FROM parsers WHERE layout_signature=%s", (sig,))


def save_schedule(schedule: Schedule, hash_hex: str, tx_hash: str) -> None:
    with _connect() as connection:
        connection.execute(
            "INSERT INTO schedules(hash,version,json,tx_hash,created_at) VALUES(%s,%s,%s,%s,%s) "
            "ON CONFLICT(hash) DO UPDATE SET version=EXCLUDED.version,json=EXCLUDED.json,tx_hash=EXCLUDED.tx_hash,created_at=EXCLUDED.created_at",
            (hash_hex, schedule.version, schedule.model_dump_json(), tx_hash, time.time()),
        )


def latest_schedule() -> Schedule | None:
    with _connect() as connection:
        row = connection.execute(
            "SELECT json FROM schedules ORDER BY version DESC,created_at DESC LIMIT 1"
        ).fetchone()
    return Schedule.model_validate_json(row[0]) if row else None


def save_option(option: RelaxOption) -> None:
    with _connect() as connection:
        connection.execute(
            "INSERT INTO options(id,json) VALUES(%s,%s) ON CONFLICT(id) DO UPDATE SET json=EXCLUDED.json",
            (option.id, option.model_dump_json()),
        )


def get_option(option_id: str) -> RelaxOption:
    with _connect() as connection:
        row = connection.execute("SELECT json FROM options WHERE id=%s", (option_id,)).fetchone()
    if not row:
        raise LookupError(f"Option {option_id} was not found")
    return RelaxOption.model_validate_json(row[0])


def next_option_id() -> str:
    return _next_id("options", "options", r"O(\d+)", "O")


def log_llm_call(fn: str, model: str, tokens_in: int, tokens_out: int, ms: int, mock: bool) -> None:
    with _connect() as connection:
        connection.execute(
            "INSERT INTO llm_calls(fn,model,tokens_in,tokens_out,ms,mock,ts) VALUES(%s,%s,%s,%s,%s,%s,%s)",
            (fn, model, tokens_in, tokens_out, ms, mock, time.time()),
        )


def tokens_since(ts: float) -> int:
    with _connect() as connection:
        row = connection.execute(
            "SELECT COALESCE(SUM(tokens_in+tokens_out),0) FROM llm_calls WHERE ts>=%s", (ts,)
        ).fetchone()
    return int(row[0])


def save_upload(filename: str, data: bytes) -> None:
    if not filename or Path(filename).name != filename or filename in {".", ".."}:
        raise ValueError("invalid upload filename")
    folder = config.UPLOAD_DIR
    folder.mkdir(parents=True, exist_ok=True)
    target = folder / filename
    temp = target.with_name(target.name + ".tmp")
    temp.write_bytes(data)
    temp.replace(target)


def get_upload(filename: str) -> bytes | None:
    if not filename or Path(filename).name != filename:
        return None
    path = config.UPLOAD_DIR / filename
    return path.read_bytes() if path.is_file() else None


init_db()
